@ECHO OFF


set /p dir=Enter this project name:

REM Function to create directories
  mkdir "Assets\%dir%\Scenes"
  mkdir "Assets\%dir%\Prefabs"
  mkdir "Assets\%dir%\Scripts"
  mkdir "Assets\%dir%\Animations"
  mkdir "Assets\%dir%\Materials"
  mkdir "Assets\%dir%\Physics Materials"
  mkdir "Assets\%dir%\Fonts"
  mkdir "Assets\%dir%\Textures"
  mkdir "Assets\%dir%\Audio"
  mkdir "Assets\%dir%\Resources"
  mkdir "Assets\%dir%\Editor"
  mkdir "Assets\%dir%\Plugins"

REM Creating .gitignore file
(
  echo /[Ll]ibrary/
  echo /[Tt]emp/
  echo /[Oo]bj/
  echo /[Bb]uild/
  echo /[Bb]uilds/
  echo /[Ll]ogs/
  echo /Assets/AssetStoreTools*
  echo.
  echo # Autogenerated VS/MD solution and project files
  echo ExportedObj/
  echo *.csproj
  echo *.unityproj
  echo *.sln
  echo *.suo
  echo *.tmp
  echo *.user
  echo *.userprefs
  echo *.pidb
  echo *.booproj
  echo *.svd
  echo.
  echo # Unity3D generated meta files
  echo *.pidb.meta
  echo.
  echo # Unity3D Generated File On Crash Reports
  echo sysinfo.txt
  echo.
  echo # Builds
  echo *.apk
  echo *.unitypackage
  echo.
  echo # Visual Studio
  echo .vs
  echo Release/
  echo Debug/
) > .gitignore

REM Creating .gitattributes file
(
  echo ## Unity ##
  echo.
  echo *.cs diff=csharp text
  echo *.cginc text
  echo *.shader text
  echo.
  echo *.mat merge=unityyamlmerge eol=lf
  echo *.anim merge=unityyamlmerge eol=lf
  echo *.unity merge=unityyamlmerge eol=lf
  echo *.prefab merge=unityyamlmerge eol=lf
  echo *.physicsMaterial2D merge=unityyamlmerge eol=lf
  echo *.physicMaterial merge=unityyamlmerge eol=lf
  echo *.asset merge=unityyamlmerge eol=lf
  echo *.meta merge=unityyamlmerge eol=lf
  echo *.controller merge=unityyamlmerge eol=lf
  echo.
  echo ## git-lfs ##
  echo.
  echo REM Image
  echo *.jpg filter=lfs diff=lfs merge=lfs -text
  echo *.jpeg filter=lfs diff=lfs merge=lfs -text
  echo *.png filter=lfs diff=lfs merge=lfs -text
  echo *.gif filter=lfs diff=lfs merge=lfs -text
  echo *.psd filter=lfs diff=lfs merge=lfs -text
  echo *.ai filter=lfs diff=lfs merge=lfs -text
  echo.
  echo REM Audio
  echo *.mp3 filter=lfs diff=lfs merge=lfs -text
  echo *.wav filter=lfs diff=lfs merge=lfs -text
  echo *.ogg filter=lfs diff=lfs merge=lfs -text
  echo.
  echo REM Video
  echo *.mp4 filter=lfs diff=lfs merge=lfs -text
  echo *.mov filter=lfs diff=lfs merge=lfs -text
  echo.
  echo REM 3D Object
  echo *.FBX filter=lfs diff=lfs merge=lfs -text
  echo *.fbx filter=lfs diff=lfs merge=lfs -text
  echo *.blend filter=lfs diff=lfs merge=lfs -text
  echo *.obj filter=lfs diff=lfs merge=lfs -text
  echo.
  echo REM ETC
  echo *.a filter=lfs diff=lfs merge=lfs -text
  echo *.exr filter=lfs diff=lfs merge=lfs -text
  echo *.tga filter=lfs diff=lfs merge=lfs -text
  echo *.pdf filter=lfs diff=lfs merge=lfs -text
  echo *.zip filter=lfs diff=lfs merge=lfs -text
  echo *.dll filter=lfs diff=lfs merge=lfs -text
  echo *.unitypackage filter=lfs diff=lfs merge=lfs -text
  echo *.aif filter=lfs diff=lfs merge=lfs -text
  echo *.ttf filter=lfs diff=lfs merge=lfs -text
  echo *.rns filter=lfs diff=lfs merge=lfs -text
  echo *.reason filter=lfs diff=lfs merge=lfs -text
  echo *.lxo filter=lfs diff=lfs merge=lfs -text
) > .gitattributes


  ECHO Setup .gitignore and Asset directories.
  ECHO done.

PAUSE
